# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68789c03a502efbca025773f11f231cadc8cc627e12d507d8adc0cf2764dad3af145c4fe05477721738c80d4a29e0e6b3911fb3cdd94ef0f9944fdd4f6de545c

test:
  secret_key_base: d6c063f6702562fbf63063c246599311660f6e82c17ceaacb2305752292a655178d7167ec3eb08bb9ae98236f4107dab61ed1d28c01c4cf0573381a244835819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis:
    url: <%= ENV["REDISTOGO_URL"] %>
    host: <%= ENV["REDIS_HOST"] %>
    port: <%= ENV["REDIS_PORT"] %>
    password: <%= ENV["REDIS_PASSWORD"] %>
